In [1158]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [1159]:
df = pd.read_csv("SUPERSTORE_DATASET.csv", sep=',')

In [1160]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2019-103800,2019-01-03,2019-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,CA-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
2,CA-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
3,CA-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
4,CA-2019-141817,2019-01-05,2019-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [1161]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9994 non-null   str
 1   Order Date     9994 non-null   str
 2   Ship Date      9994 non-null   str
 3   Ship Mode      9994 non-null   str
 4   Customer ID    9994 non-null   str
 5   Customer Name  9994 non-null   str
 6   Segment        9994 non-null   str
 7   Country        9994 non-null   str
 8   City           9994 non-null   str
 9   State          9994 non-null   str
 10  Postal Code    9994 non-null   int64
 11  Region         9994 non-null   str
 12  Product ID     9994 non-null   str
 13  Category       9994 non-null   str
 14  Sub-Category   9994 non-null   str
 15  Product Name   9994 non-null   str
 16  Sales          9994 non-null   float64
 17  Quantity       9994 non-null   int64
 18  Discount       9994 non-null   float64
 19  Profit         9994 non-null   float64
dtypes: float64(3), int64(2), str(15)
memory usage: 1.5 MB

In [1162]:
# PADRONIZAÇÃO DE CONTEÚDO STRING

df.columns = df.columns.str.upper()
df.columns = df.columns.str.replace(" ", "_")
string_cols = df.select_dtypes(include=['string']).columns
df[string_cols] = df[string_cols].apply(lambda x: x.str.upper())

In [1163]:
df.head()

,ORDER_ID,ORDER_DATE,SHIP_DATE,SHIP_MODE,CUSTOMER_ID,CUSTOMER_NAME,SEGMENT,COUNTRY,CITY,STATE,POSTAL_CODE,REGION,PRODUCT_ID,CATEGORY,SUB-CATEGORY,PRODUCT_NAME,SALES,QUANTITY,DISCOUNT,PROFIT
0,CA-2019-103800,2019-01-03,2019-01-07,STANDARD CLASS,DP-13000,DARREN POWERS,CONSUMER,UNITED STATES,HOUSTON,TEXAS,77095,CENTRAL,OFF-PA-10000174,OFFICE SUPPLIES,PAPER,"MESSAGE BOOK, WIREBOUND, FOUR 5 1/2"" X 4"" FORM...",16.448,2,0.2,5.5512
1,CA-2019-112326,2019-01-04,2019-01-08,STANDARD CLASS,PO-19195,PHILLINA OBER,HOME OFFICE,UNITED STATES,NAPERVILLE,ILLINOIS,60540,CENTRAL,OFF-LA-10003223,OFFICE SUPPLIES,LABELS,AVERY 508,11.784,3,0.2,4.2717
2,CA-2019-112326,2019-01-04,2019-01-08,STANDARD CLASS,PO-19195,PHILLINA OBER,HOME OFFICE,UNITED STATES,NAPERVILLE,ILLINOIS,60540,CENTRAL,OFF-ST-10002743,OFFICE SUPPLIES,STORAGE,SAFCO BOLTLESS STEEL SHELVING,272.736,3,0.2,-64.7748
3,CA-2019-112326,2019-01-04,2019-01-08,STANDARD CLASS,PO-19195,PHILLINA OBER,HOME OFFICE,UNITED STATES,NAPERVILLE,ILLINOIS,60540,CENTRAL,OFF-BI-10004094,OFFICE SUPPLIES,BINDERS,GBC STANDARD PLASTIC BINDING SYSTEMS COMBS,3.540,2,0.8,-5.4870
4,CA-2019-141817,2019-01-05,2019-01-12,STANDARD CLASS,MB-18085,MICK BROWN,CONSUMER,UNITED STATES,PHILADELPHIA,PENNSYLVANIA,19143,EAST,OFF-AR-10003478,OFFICE SUPPLIES,ART,AVERY HI-LITER EVERBOLD PEN STYLE FLUORESCENT ...,19.536,3,0.2,4.8840

In [1164]:
df.isnull().sum()

ORDER_ID         0
ORDER_DATE       0
SHIP_DATE        0
SHIP_MODE        0
CUSTOMER_ID      0
CUSTOMER_NAME    0
SEGMENT          0
COUNTRY          0
CITY             0
STATE            0
POSTAL_CODE      0
REGION           0
PRODUCT_ID       0
CATEGORY         0
SUB-CATEGORY     0
PRODUCT_NAME     0
SALES            0
QUANTITY         0
DISCOUNT         0
PROFIT           0
dtype: int64

In [1165]:


df = df.drop_duplicates(subset='ORDER_ID')

# Eliminação de colunas desnecessárias
df = df.drop(columns=['CUSTOMER_NAME', 'POSTAL_CODE', 'ORDER_ID'])


# Padronização de dados temporais
df['ORDER_DATE'] = pd.to_datetime(df['ORDER_DATE'])
df['SHIP_DATE'] = pd.to_datetime(df['SHIP_DATE'])
df = df[df['SHIP_DATE'] >= df['ORDER_DATE']]

# Padronização de dados geográficos
state_map = {
    'ALABAMA': 'AL', 'ALASKA': 'AK', 'ARIZONA': 'AZ', 'ARKANSAS': 'AR',
    'CALIFORNIA': 'CA', 'COLORADO': 'CO', 'CONNECTICUT': 'CT',
    'DELAWARE': 'DE', 'FLORIDA': 'FL', 'GEORGIA': 'GA',
    'HAWAII': 'HI', 'IDAHO': 'ID', 'ILLINOIS': 'IL',
    'INDIANA': 'IN', 'IOWA': 'IA', 'KANSAS': 'KS',
    'KENTUCKY': 'KY', 'LOUISIANA': 'LA', 'MAINE': 'ME',
    'MARYLAND': 'MD', 'MASSACHUSETTS': 'MA', 'MICHIGAN': 'MI',
    'MINNESOTA': 'MN', 'MISSISSIPPI': 'MS', 'MISSOURI': 'MO',
    'MONTANA': 'MT', 'NEBRASKA': 'NE', 'NEVADA': 'NV',
    'NEW HAMPSHIRE': 'NH', 'NEW JERSEY': 'NJ', 'NEW MEXICO': 'NM',
    'NEW YORK': 'NY', 'NORTH CAROLINA': 'NC', 'NORTH DAKOTA': 'ND',
    'OHIO': 'OH', 'OKLAHOMA': 'OK', 'OREGON': 'OR',
    'PENNSYLVANIA': 'PA', 'RHODE ISLAND': 'RI',
    'SOUTH CAROLINA': 'SC', 'SOUTH DAKOTA': 'SD',
    'TENNESSEE': 'TN', 'TEXAS': 'TX', 'UTAH': 'UT',
    'VERMONT': 'VT', 'VIRGINIA': 'VA', 'WASHINGTON': 'WA',
    'WEST VIRGINIA': 'WV', 'WISCONSIN': 'WI', 'WYOMING': 'WY',
    'DISTRICT OF COLUMBIA': 'DC'
}

df['STATE'] = df['STATE'].map(state_map)
df['COUNTRY'] = df['COUNTRY'].map({'UNITED STATES': 'USA'})
df['NET_SALES'] = df['SALES'] * df['QUANTITY'] * (1-df['DISCOUNT'])

df = df.rename(columns={"SUB-CATEGORY": "SUB_CATEGORY"})

In [1166]:
df.head()

,ORDER_DATE,SHIP_DATE,SHIP_MODE,CUSTOMER_ID,SEGMENT,COUNTRY,CITY,STATE,REGION,PRODUCT_ID,CATEGORY,SUB_CATEGORY,PRODUCT_NAME,SALES,QUANTITY,DISCOUNT,PROFIT,NET_SALES
0,2019-01-03,2019-01-07,STANDARD CLASS,DP-13000,CONSUMER,USA,HOUSTON,TX,CENTRAL,OFF-PA-10000174,OFFICE SUPPLIES,PAPER,"MESSAGE BOOK, WIREBOUND, FOUR 5 1/2"" X 4"" FORM...",16.448,2,0.2,5.5512,26.3168
1,2019-01-04,2019-01-08,STANDARD CLASS,PO-19195,HOME OFFICE,USA,NAPERVILLE,IL,CENTRAL,OFF-LA-10003223,OFFICE SUPPLIES,LABELS,AVERY 508,11.784,3,0.2,4.2717,28.2816
4,2019-01-05,2019-01-12,STANDARD CLASS,MB-18085,CONSUMER,USA,PHILADELPHIA,PA,EAST,OFF-AR-10003478,OFFICE SUPPLIES,ART,AVERY HI-LITER EVERBOLD PEN STYLE FLUORESCENT ...,19.536,3,0.2,4.8840,46.8864
5,2019-01-06,2019-01-10,STANDARD CLASS,ME-17320,HOME OFFICE,USA,HENDERSON,KY,SOUTH,OFF-AR-10001662,OFFICE SUPPLIES,ART,ROGERS HANDHELD BARREL PENCIL SHARPENER,5.480,2,0.0,1.4796,10.9600
8,2019-01-06,2019-01-07,FIRST CLASS,JO-15145,CORPORATE,USA,ATHENS,GA,SOUTH,OFF-AR-10002399,OFFICE SUPPLIES,ART,"DIXON PRANG WATERCOLOR PENCILS, 10-COLOR SET W...",12.780,3,0.0,5.2398,38.3400

# Preparação para modelagem

## Modelo preditivo

In [1167]:
df_preditivo = df.copy()

## Modelo de classificação

In [1168]:
df_clustering = df[['SHIP_MODE', 'CUSTOMER_ID', 'SEGMENT', 'REGION', 'CATEGORY', 'SUB_CATEGORY', 'NET_SALES', 'PROFIT']]
df_clustering = df_clustering.reset_index(drop=True)

df_clustering = df_clustering.groupby('CUSTOMER_ID', as_index=False).agg({
    'SHIP_MODE': 'first',
    'SEGMENT': 'first',
    'REGION': 'first',
    'CATEGORY': 'first',
    'SUB_CATEGORY': 'first',
    'NET_SALES': 'sum',
    'PROFIT': 'sum'
})

df_clustering = df_clustering.drop(columns='CUSTOMER_ID')
X_scaled = df_clustering.copy()

In [1169]:
df_clustering.head()

,SHIP_MODE,SEGMENT,REGION,CATEGORY,SUB_CATEGORY,NET_SALES,PROFIT
0,STANDARD CLASS,CONSUMER,WEST,OFFICE SUPPLIES,APPLIANCES,10725.69280,-666.4136
1,STANDARD CLASS,CONSUMER,WEST,OFFICE SUPPLIES,BINDERS,2179.55640,206.9757
2,SAME DAY,CONSUMER,EAST,FURNITURE,FURNISHINGS,2148.77480,161.5842
3,STANDARD CLASS,CONSUMER,EAST,FURNITURE,CHAIRS,15335.94625,648.0864
4,STANDARD CLASS,CONSUMER,CENTRAL,OFFICE SUPPLIES,STORAGE,503.12800,65.1097

In [1170]:
cols_one_hot = ['SHIP_MODE', 'SEGMENT', 'REGION']

for col in cols_one_hot:
    print(df_clustering[col].value_counts(), "\n")

SHIP_MODE
STANDARD CLASS    481
SECOND CLASS      157
FIRST CLASS       118
SAME DAY           37
Name: count, dtype: int64

SEGMENT
CONSUMER       409
CORPORATE      236
HOME OFFICE    148
Name: count, dtype: int64

REGION
WEST       252
EAST       204
CENTRAL    196
SOUTH      141
Name: count, dtype: int64

In [1171]:
X_scaled = pd.get_dummies(
    X_scaled,
    columns=['REGION', 'SEGMENT', 'SHIP_MODE'],
    drop_first=True
)

In [1172]:
cols_freq = ['CATEGORY', 'SUB_CATEGORY']  

for col in cols_freq:
    freq = X_scaled[col].value_counts(normalize=True)
    X_scaled[col] = X_scaled[col].map(freq)

In [1173]:
cols_scaler = ['PROFIT', 'NET_SALES']

scaler = StandardScaler()
X_scaled[cols_scaler] = scaler.fit_transform(X_scaled[cols_scaler])

In [1174]:
X_scaled.head()

,CATEGORY,SUB_CATEGORY,NET_SALES,PROFIT,REGION_EAST,REGION_SOUTH,REGION_WEST,SEGMENT_CORPORATE,SEGMENT_HOME OFFICE,SHIP_MODE_SAME DAY,SHIP_MODE_SECOND CLASS,SHIP_MODE_STANDARD CLASS
0,0.621690,0.047919,0.484276,-1.474409,False,False,True,False,False,False,False,True
1,0.621690,0.156368,-0.457770,0.010157,False,False,True,False,False,False,False,True
2,0.211854,0.089533,-0.461163,-0.066998,True,False,False,False,False,True,False,False
3,0.211854,0.061791,0.992467,0.759946,True,False,False,False,False,False,False,True
4,0.621690,0.083228,-0.642564,-0.230983,False,False,False,False,False,False,False,True