In [1]:
import pandas as pd
import plotly.express as px
import numpy as np
from pathlib import Path

In [2]:
data_file = Path("..") / "data" / "data_processed" / "SUPERSTORE_DATASET_TRATADO.csv"
df = pd.read_csv(data_file, sep=",")

In [3]:
df.head()

,ORDER_DATE,SHIP_DATE,SHIP_MODE,CUSTOMER_ID,SEGMENT,COUNTRY,CITY,STATE,REGION,PRODUCT_ID,CATEGORY,SUB_CATEGORY,PRODUCT_NAME,PROFIT,NET_SALES
0,2019-01-03,2019-01-07,STANDARD CLASS,DP-13000,CONSUMER,USA,HOUSTON,TX,CENTRAL,OFF-PA-10000174,OFFICE SUPPLIES,PAPER,"MESSAGE BOOK, WIREBOUND, FOUR 5 1/2"" X 4"" FORM...",5.5512,26.3168
1,2019-01-04,2019-01-08,STANDARD CLASS,PO-19195,HOME OFFICE,USA,NAPERVILLE,IL,CENTRAL,OFF-LA-10003223,OFFICE SUPPLIES,LABELS,AVERY 508,4.2717,28.2816
2,2019-01-05,2019-01-12,STANDARD CLASS,MB-18085,CONSUMER,USA,PHILADELPHIA,PA,EAST,OFF-AR-10003478,OFFICE SUPPLIES,ART,AVERY HI-LITER EVERBOLD PEN STYLE FLUORESCENT ...,4.8840,46.8864
3,2019-01-06,2019-01-10,STANDARD CLASS,ME-17320,HOME OFFICE,USA,HENDERSON,KY,SOUTH,OFF-AR-10001662,OFFICE SUPPLIES,ART,ROGERS HANDHELD BARREL PENCIL SHARPENER,1.4796,10.9600
4,2019-01-06,2019-01-07,FIRST CLASS,JO-15145,CORPORATE,USA,ATHENS,GA,SOUTH,OFF-AR-10002399,OFFICE SUPPLIES,ART,"DIXON PRANG WATERCOLOR PENCILS, 10-COLOR SET W...",5.2398,38.3400

In [4]:
df_filtered = df.copy()
analise_de_outliers = ['PROFIT', 'NET_SALES']

for col in analise_de_outliers:
    fig_1 = px.histogram(df_filtered, x=col, title=col)
    fig_2 = px.box(df_filtered, y=col, title=col)
    fig_1.show()
    fig_2.show()

In [5]:


df_filtered['NET_SALES_LOG'] = np.log1p(df['NET_SALES'])

analise_de_outliers = ['PROFIT', 'NET_SALES_LOG']


for col in analise_de_outliers:
    Q1 = df_filtered[col].quantile(0.15)
    Q3 = df_filtered[col].quantile(0.85)
    IQR = Q3 - Q1
    df_filtered = df_filtered[(df_filtered[col] >= Q1 - 1.5*IQR) & (df_filtered[col] <= Q3 + 1.5*IQR)]

print(round((df.shape[0] - df_filtered.shape[0]) / df.shape[0],4)*100)

8.94

In [6]:
for col in analise_de_outliers:
    fig_1 = px.histogram(df_filtered, x=col, title=col)
    fig_2 = px.box(df_filtered, y=col, title=col)
    fig_1.show()
    fig_2.show()

In [7]:
df_filtered.head()

,ORDER_DATE,SHIP_DATE,SHIP_MODE,CUSTOMER_ID,SEGMENT,COUNTRY,CITY,STATE,REGION,PRODUCT_ID,CATEGORY,SUB_CATEGORY,PRODUCT_NAME,PROFIT,NET_SALES,NET_SALES_LOG
0,2019-01-03,2019-01-07,STANDARD CLASS,DP-13000,CONSUMER,USA,HOUSTON,TX,CENTRAL,OFF-PA-10000174,OFFICE SUPPLIES,PAPER,"MESSAGE BOOK, WIREBOUND, FOUR 5 1/2"" X 4"" FORM...",5.5512,26.3168,3.307502
1,2019-01-04,2019-01-08,STANDARD CLASS,PO-19195,HOME OFFICE,USA,NAPERVILLE,IL,CENTRAL,OFF-LA-10003223,OFFICE SUPPLIES,LABELS,AVERY 508,4.2717,28.2816,3.376959
2,2019-01-05,2019-01-12,STANDARD CLASS,MB-18085,CONSUMER,USA,PHILADELPHIA,PA,EAST,OFF-AR-10003478,OFFICE SUPPLIES,ART,AVERY HI-LITER EVERBOLD PEN STYLE FLUORESCENT ...,4.8840,46.8864,3.868832
3,2019-01-06,2019-01-10,STANDARD CLASS,ME-17320,HOME OFFICE,USA,HENDERSON,KY,SOUTH,OFF-AR-10001662,OFFICE SUPPLIES,ART,ROGERS HANDHELD BARREL PENCIL SHARPENER,1.4796,10.9600,2.481568
4,2019-01-06,2019-01-07,FIRST CLASS,JO-15145,CORPORATE,USA,ATHENS,GA,SOUTH,OFF-AR-10002399,OFFICE SUPPLIES,ART,"DIXON PRANG WATERCOLOR PENCILS, 10-COLOR SET W...",5.2398,38.3400,3.672242